version: '3.8'
services:
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hero
    # volumes:
    #   - db-data:/var/lib/postgresql/data2
    ports:
      - "5432:5432"